Repository dnd-side-project/dnd-7th-1-backend, pull requests merged in 2022-09, with the labels that each got.

#116 [FEAT | FIX] JWT 구현 및 걸음수 랭킹 오류 해결
  build.gradle
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTSignFilter.java
  src/main/java/com/dnd/ground/global/util/JwtUtil.java
  src/main/java/com/dnd/ground/global/util/JwtVerifyResult.java
  src/main/resources/data.sql
Labels: BUG, FEAT

#119 [MODIFY] 회원 인증/인가 및 로그인 관련 로직 분리
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTSignFilter.java
Labels: MODIFY

#120 FEAT: 닉네임 유효성 검사 기능 구현
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
Labels: FEAT

#121 FEAT: 프로필 관련 추가
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/resources/data.sql
Labels: FEAT

#123 [FEAT] JWT 로직 수정
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTSignFilter.java
Labels: MODIFY

#122 FEAT: S3관련 서비스 추가
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/dto/KakaoDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
  src/main/java/com/dnd/ground/global/util/AmazonS3Service.java
Labels: FEAT

#124 [MODIFY] JWTCheckFilter 전체적인 로직 수정
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
Labels: MODIFY

#126 [FEAT] 회원가입 로직 추가 등
  build.gradle
  git
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
  src/main/resources/data.sql
Labels: MODIFY, FEAT

#127 FIX: 필터 데이터타입 변경
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
Labels: MODIFY

#128 [FEAT] 최종 발표 이후 업데이트 반영
  .gitignore
  build.gradle
  git
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeMapResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/dto/KakaoDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/config/TomcatConfig.java
  src/main/java/com/dnd/ground/global/exception/CExceedChallengeException.java
  src/main/java/com/dnd/ground/global/exception/CNotFoundException.java
  src/main/java/com/dnd/ground/global/exception/CNotValidationException.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/ground/global/exception/ErrorCode.java
  src/main/java/com/dnd/ground/global/exception/ErrorResponse.java
  src/main/java/com/dnd/ground/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTSignFilter.java
  src/main/java/com/dnd/ground/global/util/AmazonS3Service.java
  src/main/java/com/dnd/ground/global/util/JwtUtil.java
  src/main/java/com/dnd/ground/global/util/JwtVerifyResult.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: MODIFY, FEAT, CHORE, ADD

#129 [FEAT] 최종 발표 이후 업데이트 반영
  .gitignore
  build.gradle
  git
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeMapResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/dto/KakaoDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/config/TomcatConfig.java
  src/main/java/com/dnd/ground/global/exception/CExceedChallengeException.java
  src/main/java/com/dnd/ground/global/exception/CNotFoundException.java
  src/main/java/com/dnd/ground/global/exception/CNotValidationException.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/ground/global/exception/ErrorCode.java
  src/main/java/com/dnd/ground/global/exception/ErrorResponse.java
  src/main/java/com/dnd/ground/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTSignFilter.java
  src/main/java/com/dnd/ground/global/util/AmazonS3Service.java
  src/main/java/com/dnd/ground/global/util/JwtUtil.java
  src/main/java/com/dnd/ground/global/util/JwtVerifyResult.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: BUG, MODIFY, FEAT

#130 [FEAT | FIX] 특정 url에 대해 시큐리티 룰을 무시하는 코드 구현
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
Labels: BUG

#132 [ADD] 닉네임 중복검사 api를 스프링 시큐리티 룰에서 제외
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
Labels: ADD

#133 [FEAT] 토큰 재발급 api 구현 및 로직 수정
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/dnd/ground/global/securityFilter/JWTCheckFilter.java
Labels: MODIFY, FEAT

#134 ADD: Swagger에 JWT 인증 관련 설정 추가
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SwaggerConfig.java
Labels: ADD

#135 [FEAT] 운동 기록 날짜 조회 api 구현
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: FEAT
