Repository dnd-side-project/dnd-7th-1-backend, pull requests merged in 2022-08, with the labels that each got.

#34 [MODIFY] User, Friend 수정
  src/main/java/com/dnd/ground/domain/friend/Friend.java
  src/main/java/com/dnd/ground/domain/user/User.java
Labels: MODIFY

#38 [FEAT] 챌린지 생성 기능 구현 등
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImplTest.java
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: MODIFY, FEAT, CHORE

#39 [FEAT] 친구 목록 조회, 챌린지 생성 기능 구현 및 메인 지도 DTO 생성
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/Friend.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/QueryDslConfig.java
  src/main/java/com/dnd/ground/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/GroundApplication.java
  src/test/java/com/dnd/ground/GroundApplicationTests.java
  src/test/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImplTest.java
  src/test/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceTest.java
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: MODIFY, FEAT, CHORE

#40 [FEAT] 친구 목록 조회, 챌린지 생성 기능 구현 및 메인 지도 DTO 생성
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/Friend.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/QueryDslConfig.java
  src/main/java/com/dnd/ground/global/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/GroundApplication.java
  src/test/java/com/dnd/ground/GroundApplicationTests.java
  src/test/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImplTest.java
  src/test/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceTest.java
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: DOCS, MODIFY, FEAT, CHORE

#41 [FEAT] DTO 및 유저 운동 기록 관리
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/test/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceTest.java
Labels: MODIFY, FEAT

#43 [ADD] 챌린지 UUID 필드 추가 및 started 필드 데이터 타입 변경
  build.gradle
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/global/util/UuidUtil.java
Labels: ADD

#48 [ADD] 홈 화면, 기록 api 명세 추가 및 중복 칸 관리
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, ADD

#49 [FEAT] 챌린지 관련 조회 기능 추가
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: FEAT

#50 [MODIFY] 메인화면 조회 시 챌린지 관련 로직 변경
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#53 [FEAT] 랭킹 페이지 api 구현(칸의 수, 영역의 수 기준)
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#56 FEAT: 회원의 마지막 위치 관리 및 반환
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#57 [FEAT] 랭킹 순위 추가
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: FEAT, ADD

#58 FEAT: 일주일 챌린지 상태 관리 및 종류 추가
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeType.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/resources/data.sql
Labels: FEAT, ADD

#60 [MODIFY] 코드 가독성 개선
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
Labels: MODIFY, FEAT

#61 [MERGE] 개발 사항 병합
  build.gradle
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeType.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/util/UuidUtil.java
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceTest.java
Labels: MODIFY, FEAT, ADD

#62 [MERGE] 개발 사항 병합
  build.gradle
  src/main/java/com/dnd/ground/GroundApplication.java
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeType.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordQueryRepositoryImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/util/UuidUtil.java
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceTest.java
Labels: MODIFY, FEAT, ADD

#64 [MODIFY] API 명세 정리 및 설정파일 수정
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/global/SwaggerController.java
  src/main/resources/application.yml
Labels: MODIFY, CHORE

#66 [REFACTOR] 매트릭스 조회 방식 변경
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/SwaggerController.java
  src/main/resources/application.yml
Labels: MODIFY, FEAT

#67 [MODIFY] 랭킹 관련 메소드 이동
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixController.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#70 [FEAT | MODIFY] 회원 관련 필드명 수정 및 회원 정보 조회 기능 구현
  .gitignore
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: MODIFY, FEAT

#72 [FEAT | FIX] 운동기록에 거리, 걸음수, 시간 추가 및 충돌 해결
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: ADD

#73 [FEAT] 걸음수 랭킹 조회 기능 및 랭킹dto 재구성
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixController.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
Labels: MODIFY, FEAT

#74 [FEAT] 챌린지 조회 기능 구현
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: FEAT

#75 [FEAT] 마이페이지 api 구현
  README.md
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: MODIFY, FEAT, ADD

#76 [FEAT] 회원 프로필 조회 기능 구현
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: FEAT

#77 [ADD | MODIFY] 마이페이지 api명세 추가 및 친구 프로필 영역의 수 로직 수정
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/data.sql
Labels: MODIFY, ADD

#78 [CHORE]Open-In-View=false 설정 추가
  src/main/resources/application.yml
Labels: CHORE

#79 [MODIFY] 챌린지 색상 관련 수정
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeColor.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, ADD

#80 [FEAT] 마이 페이지, 활동 기록, 운동 기록 조회 기능 구현
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/ActivityRecordResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#81 FEAT: 챌린지 상세 정보 조회 기능 구현
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/resources/application.yml
Labels: MODIFY, FEAT

#82 [MODIFY] api 명세 수정 및 운동 시간 관련 필드 포맷팅
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/ActivityRecordResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: MODIFY

#83 [FEAT | MODIFY] 유저와 관련된 request dto 생성 및 역대 누적 랭킹 조회 기능
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixController.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#85 [CHORE | MODIFY] API 명세 수정, OSIV 설정 변경
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: MODIFY, ADD

#86 [FEAT | MODIFY] 운동 기록에서 참여한 챌린지 조회 및 기록 api 수정
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#87 [FEAT] 메인화면 필터 관련 기능 구현 및 챌린지 조회 기능 수정
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: MODIFY, FEAT

#88 [FEAT] 마이페이지, 프로필, 챌린지, 랭킹, 필터 관련 api 구현
  .gitignore
  README.md
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeColor.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixController.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/ActivityRecordResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/SwaggerController.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: MODIFY, FEAT, CHORE, ADD

#89 [FEAT] 마이페이지, 프로필, 챌린지, 랭킹, 필터 관련 API구현
  .gitignore
  README.md
  src/main/java/com/dnd/ground/domain/challenge/Challenge.java
  src/main/java/com/dnd/ground/domain/challenge/ChallengeColor.java
  src/main/java/com/dnd/ground/domain/challenge/UserChallenge.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/Matrix.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixController.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixSetDto.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/ActivityRecordResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/HomeResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/RankResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/dnd/ground/domain/friend/FriendTest.java
Labels: MODIFY, FEAT, ADD

#90 [FEAT] 운동기록 메시지, 유저 프로필 수정 api 구현
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/RecordRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/dto/MatrixDto.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, FEAT

#91 MODIFY: 필터에 따른 메인화면 조회 메소드 수정
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#93 [MODIFY] 칸 정보 반환 타입 변경
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
Labels: MODIFY

#96 [ADD] 기록 끝날시 시작, 끝 시간 받아오는 코드 추가
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
Labels: MODIFY, ADD

#97 FIX: 메인화면 조회 과정에서 챌린지 멤버를 조회하지 못하는 문제 수정
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: BUG

#100 [MODIFY] 마이페이지 api 수정
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY, ADD

#105 [FEAT] 전역 예외 처리 구현
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/exception/CNotFoundException.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/ErrorCode.java
  src/main/java/com/dnd/ground/global/exception/ErrorResponse.java
  src/main/java/com/dnd/ground/global/exception/GlobalExceptionHandler.java
Labels: MODIFY, FEAT

#107 [ADD] 각 상황에 따른 예외 처리 추가
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/global/exception/CExceedChallengeException.java
  src/main/java/com/dnd/ground/global/exception/CNotValidationException.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/java/com/dnd/ground/global/exception/ErrorResponse.java
  src/main/java/com/dnd/ground/global/exception/GlobalExceptionHandler.java
Labels: ADD

#106 [MODIFY] 랭킹 api, 기록 시작 api 수정
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/StartResponseDto.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
Labels: MODIFY, FEAT

#109 FEAT: 챌린지와 관련된 지도 조회 기능 구현
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeController.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeMapResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
Labels: FEAT

#110 [MODIFY] 컨트롤러-서비스단 전달 형태 변경
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordController.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/controller/RecordControllerImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/controller/MatrixControllerImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixService.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#111 [MODIFY] UserResponseDto 내부 클래스 이동
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#112 [FIX] 컨트롤러-서비스단 전달 형태 변경 사항 추가
  src/main/java/com/dnd/ground/domain/exerciseRecord/dto/EndRequestDto.java
Labels: BUG

#113 [FIX] 동기화
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
Labels: BUG
