Repository dnd-side-project/dnd-7th-1-backend, pull requests merged in 2022-10, with the labels that each got.

#139 [MODIFY] 나의 활동 기록에서 tatal값 삭제
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/ActivityRecordResponseDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: MODIFY

#140 [FEAT] 더미 데이터 생성 관련 로직 추가 및 DDL 옵션 변경
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/ExerciseRecord.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordService.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/matrix/matrixRepository/MatrixRepository.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/repository/UserRepository.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/java/com/dnd/ground/global/dummy/DummyController.java
  src/main/java/com/dnd/ground/global/dummy/DummyRequestDto.java
  src/main/java/com/dnd/ground/global/dummy/DummyResponseDto.java
  src/main/java/com/dnd/ground/global/dummy/DummyService.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
  src/main/resources/application.yml
Labels: FEAT, ADD

#141 [FEAT] 프로필 사진 추가
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeMapResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/Repository/ExerciseRecordRepository.java
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/resources/application.yml
Labels: FEAT, ADD

#142 FEAT: 친구 요청, 응답, 삭제 등에 대한 기능 구현
  src/main/java/com/dnd/ground/domain/friend/Friend.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendRequestDto.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
Labels: FEAT

#143 [FEAT | ADD] 유저 프로필 조회 구현 및 회원 가입 시 내 위치 공개 추가
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/JwtUserDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/dto/UserResponseDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
Labels: FEAT, ADD

#144 [FEAT] 프로필 수정 api 구현
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/util/AmazonS3Service.java
Labels: FEAT

#145 MODIFY: 챌린지 및 회원정보 수정 관련 구현
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateRequestDto.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/UserRequestDto.java
  src/main/java/com/dnd/ground/domain/user/service/AuthService.java
  src/main/java/com/dnd/ground/domain/user/service/AuthServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/service/UserService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/AmazonS3Config.java
  src/main/java/com/dnd/ground/global/exception/CommonErrorCode.java
Labels: MODIFY

#147 FEAT|MODIFY: 친구, 챌린지 관련 수정 등
  .gitignore
  build.gradle
  src/main/java/com/dnd/ground/domain/challenge/ChallengeStatus.java
  src/main/java/com/dnd/ground/domain/challenge/controller/ChallengeControllerImpl.java
  src/main/java/com/dnd/ground/domain/challenge/dto/ChallengeCreateResponseDto.java
  src/main/java/com/dnd/ground/domain/challenge/repository/ChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/repository/UserChallengeRepository.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeService.java
  src/main/java/com/dnd/ground/domain/challenge/service/ChallengeServiceImpl.java
  src/main/java/com/dnd/ground/domain/friend/FriendStatus.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendController.java
  src/main/java/com/dnd/ground/domain/friend/controller/FriendControllerImpl.java
  src/main/java/com/dnd/ground/domain/friend/dto/FriendResponseDto.java
  src/main/java/com/dnd/ground/domain/friend/repository/FriendRepository.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendService.java
  src/main/java/com/dnd/ground/domain/friend/service/FriendServiceImpl.java
  src/main/java/com/dnd/ground/domain/user/User.java
  src/main/java/com/dnd/ground/domain/user/controller/AuthController.java
  src/main/java/com/dnd/ground/domain/user/controller/UserControllerImpl.java
  src/main/java/com/dnd/ground/domain/user/dto/KakaoDto.java
  src/main/java/com/dnd/ground/domain/user/service/KakaoService.java
  src/main/java/com/dnd/ground/domain/user/service/UserServiceImpl.java
  src/main/java/com/dnd/ground/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: MODIFY, FEAT, CHORE, ADD

#146 [MODIFY] 역대 누적 칸 랭킹 dto 변경
  src/main/java/com/dnd/ground/domain/exerciseRecord/service/ExerciseRecordServiceImpl.java
  src/main/java/com/dnd/ground/domain/matrix/matrixService/MatrixServiceImpl.java
Labels: MODIFY
